export const FLAG_STATUS_PPIC_INIT = "A";
export const FLAG_STATUS_PROCUREMENT_FROM_PPIC = "B";
export const FLAG_STATUS_PROCUREMENT_RETUR = "C";
export const FLAG_STATUS_PPIC_SEND_RETUR_PROCUREMENT = "D";
export const FLAG_STATUS_SUPPLIER = "E";
export const FLAG_STATUS_PROCUREMENT_REQUEST = "F";
export const FLAG_STATUS_PPIC_REQUEST = "G";
export const FLAG_STATUS_COMPLETE_SCHEDULE = "X";
